name: shared matrix
on:
  push:
  workflow_dispatch:

jobs:
  define-matrix:
    runs-on: ubuntu-latest
    outputs:
      colors: ${{ steps.colors.outputs.colors }}
    steps:
      - name: Define Colors
        id: colors
        run: |
          echo 'colors=["red", "green", "blue"]' >> "$GITHUB_OUTPUT"

  debug-matrix:
    runs-on: ubuntu-latest
    needs: define-matrix
    steps:
      - run: echo ${{ fromJSON(needs.define-matrix.outputs.colors) }}

  consume-matrix:
    runs-on: ubuntu-latest
    needs: define-matrix
    strategy:
      matrix:
        color: ${{ fromJSON(needs.define-matrix.outputs.colors) }}
    steps:
      - id: out
        run: echo 'colors=["${{ matrix.color }}-1", "${{matrix.color}}-2", "${{matrix.color}}-3"]' >> "$GITHUB_OUTPUT"
    outputs:
      colors: ${{ steps.out.outputs.colors }}

  debug-matrix-2:
    runs-on: ubuntu-latest
    needs: consume-matrix
    steps:
      - run: echo ${{ fromJSON(needs.consume-matrix.outputs.colors) }}
      - run: echo ${{ fromJSON(fromJSON(needs.consume-matrix.outputs.colors)) }}

  consume-matrix-2:
    runs-on: ubuntu-latest
    needs: consume-matrix
    strategy:
      matrix:
        color: ${{ fromJSON(needs.consume-matrix-2.outputs.colors) }}
    steps:
      - run: echo ${{matrix.color}}
