name: test

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  shard:
    runs-on: ubuntu-latest
    outputs:
      numbers: ${{ steps.numbers.outputs.numbers }}
    steps:
      - run: |
          echo 'numbers=["1", "2", "3"]' >> $GITHUB_OUTPUT

  level-one:
    runs-on: ubuntu-latest
    needs: [shard]
    strategy:
      matrix:
        number: ${{ fromJSON(needs.shard.outputs.numbers) }}
    steps:
      - run: echo ${{matrix.number}}
